[package]
name = "sqlfmt"
version = "0.1.0"
authors = ["Thorsten Muerell <thorsten@muerell.de>"]

[build-dependencies] # <-- We added this and everything after!
lalrpop = "0.15.2"

[dependencies]
lalrpop-util = "0.15.2"
regex = "1.5.4"
colored = "2.0"
clap = "~2.32"